/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Code.*;
import java.io.File;
import javax.swing.JOptionPane;

        
public class InventoryUI extends javax.swing.JFrame {
    
    private Product[] products = new Product[100];
    private int productCount = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryUI.class.getName());

    public void addProduct(int code, String name, int quantity, double unitPrice) {
    Product newProduct = new Product(code, name, quantity, unitPrice);

    // Find correct index (sorted alphabetically by name)
    int index = 0;
    while (index < productCount && products[index].getName().compareToIgnoreCase(name) < 0) {
        index++;
    }

    // Shift elements to the right
    for (int i = productCount; i > index; i--) {
        products[i] = products[i - 1];
    }

    products[index] = newProduct;
    productCount++;

    JOptionPane.showMessageDialog(this, "Product added successfully!");
}
    public boolean deleteProduct(String name) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getName().equalsIgnoreCase(name)) {
            // Shift elements to the left
            for (int j = i; j < productCount - 1; j++) {
                products[j] = products[j + 1];
            }
            products[--productCount] = null;
            return true;
        }
    }
    return false;
}
    public boolean deleteProduct(int code) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getCode() == code) {
            for (int j = i; j < productCount - 1; j++) {
                products[j] = products[j + 1];
            }
            products[productCount - 1] = null;
            productCount--;
            return true;
        }
    }
    return false;
}

    public Product getProduct(String name) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getName().equalsIgnoreCase(name)) {
            return products[i];
        }
    }
    return null;
}   
    public Product getProduct(int code) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getCode() == code) {
            return products[i];
        }
    }
    return null;
}

    public Product getHighestStockValueProduct() {
    if (productCount == 0) return null;

    Product highest = products[0];
    for (int i = 1; i < productCount; i++) {
        if (products[i].getStockValue() > highest.getStockValue()) {
            highest = products[i];
        }
    }
    return highest;
}

    public boolean updatePrice(String name, double newPrice) {
    Product p = getProduct(name);
    if (p != null) {
        p.setUnitPrice(newPrice);
        return true;
    }
    return false;
}

    public boolean updateQuantity(String name, int additionalQuantity) {
    Product p = getProduct(name);
    if (p != null) {
        p.setQuantity(p.getQuantity() + additionalQuantity);
        return true;
    }
    return false;
}
    
    public void clear(){
        txtCode.setText("");
        txtName.setText("");
        txtQuantity.setText("");
        txtPrice.setText("");
    }

    public InventoryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnUQuantity = new javax.swing.JButton();
        btnUPrice = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnGHP = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCode.setText("Code:");

        lblName.setText("Name:");

        jLabel4.setText("Quantity:");

        jLabel5.setText("Unit Price:");

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Projects\\InventoryApp\\InventoryApp\\src\\main\\resources\\GUI\\images.jpeg")); // NOI18N

        btnUQuantity.setText("Update Quantity");
        btnUQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUQuantityActionPerformed(evt);
            }
        });

        btnUPrice.setText("Update Unit Price");
        btnUPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPriceActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnGHP.setText("Get Highest Product");
        btnGHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGHPActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(lblName)
                            .addComponent(lblCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtPrice)
                            .addComponent(txtQuantity))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUPrice)
                            .addComponent(btnUQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(33, 33, 33)
                        .addComponent(btnGHP)))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCode)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUQuantity))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(7, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch)
                    .addComponent(btnGHP))
                .addGap(27, 27, 27))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Inventory App");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String identifier = txtName.getText().trim().isEmpty() ? txtCode.getText().trim() : txtName.getText().trim();

        boolean deleted = false;
        try {
            int code = Integer.parseInt(identifier);
            deleted = deleteProduct(code);
        } catch (NumberFormatException e) {
            deleted = deleteProduct(identifier);
        }

        if (deleted) {
            clear();
            JOptionPane.showMessageDialog(this, "Product deleted successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Product not found!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         String identifier = txtName.getText().trim().isEmpty() ? txtCode.getText().trim() : txtName.getText().trim();
        Product p = null;

        try {
            int code = Integer.parseInt(identifier);
            p = getProduct(code);
        } catch (NumberFormatException e) {
            p = getProduct(identifier);
        }

        if (p != null) {
            JOptionPane.showMessageDialog(this, "Product found!" +
                "\nCode: " + p.getCode() +
                "\nName: " + p.getName() +
                "\nQuantity: " + p.getQuantity() +
                "\nUnit Price: " + p.getUnitPrice() +
                "\nTotal Value: " + p.getStockValue());
                clear();
        } else {
            JOptionPane.showMessageDialog(this, "Product not found.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGHPActionPerformed
        Product p = getHighestStockValueProduct();
    if (p != null) {
        JOptionPane.showMessageDialog(this,
            "Highest Stock Value Product:\nName: " + p.getName() +
            "\nCode: " + p.getCode() +
            "\nQuantity: " + p.getQuantity() +
            "\nUnit Price: " + p.getUnitPrice() +
            "\nStock Value: " + p.getStockValue());
    } else {
        JOptionPane.showMessageDialog(this, "No products in inventory.");
    }
    }//GEN-LAST:event_btnGHPActionPerformed

    private void btnUQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUQuantityActionPerformed
        String name = txtName.getText();
    try {
        int addQty = Integer.parseInt(txtQuantity.getText());
        if (updateQuantity(name, addQty)) {
            JOptionPane.showMessageDialog(this, "Quantity updated!");
        } else {
            JOptionPane.showMessageDialog(this, "Product not found.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid quantity value.");
    }
    }//GEN-LAST:event_btnUQuantityActionPerformed

    private void btnUPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPriceActionPerformed
         String name = txtName.getText();
    try {
        double newPrice = Double.parseDouble(txtPrice.getText());
        if (updatePrice(name, newPrice)) {
            JOptionPane.showMessageDialog(this, "Price updated!");
        } else {
            JOptionPane.showMessageDialog(this, "Product not found.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid price value.");
    }
    }//GEN-LAST:event_btnUPriceActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            int code = Integer.parseInt(txtCode.getText());
            String name = txtName.getText();
            int quantity = Integer.parseInt(txtQuantity.getText());
            double unitPrice = Double.parseDouble(txtPrice.getText());

            addProduct(code, name, quantity, unitPrice);
            txtCode.setText("");
            txtName.setText("");
            txtQuantity.setText("");
            txtPrice.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid values!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtCode.setText("");
        txtName.setText("");
        txtQuantity.setText("");
        txtPrice.setText("");
        JOptionPane.showMessageDialog(this, "Cleared");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> new InventoryUI().setVisible(true));
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGHP;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUPrice;
    private javax.swing.JButton btnUQuantity;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
